//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySklad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationItems
    {
        public long Id { get; set; }
        public long OrganizationId { get; set; }
        public long ItemId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
